---
meta:
    description:
        Creates an input and output Kinesis stream for an event processing pipeline
    dependencies:
        # Depends on the S3 bucket deployed by the storage layer
        - storage
    parameters:
        pipeline_name: 
            description: The name of the event processing pipeline
            value: rawpipe
        s3_config:
            description:
                S3 delivery configuration options
            value:
                bucket_name:
                    ref:
                        parser: output
                        parameters:
                            layer_name: storage
                            output_name: BucketName
                # We use almost no buffering to make debugging easier. These
                # settings should be changed when we deploy in production.
                buffer_mbs: 1
                buffer_seconds: 60
                compression: GZIP
        input_stream:
            description:
                Properties of the input Kinesis stream
            value:
                shard_count: 1
                batch_size: 1
        output_stream:
            description:
                Properties of the output Kinesis stream
            value:
                shard_count: 1
                batch_size: 1
        firehose_resource_function_arn:
            description:
                The ARN of the Lambda function that backs the custom Firehose resource
            value:
                ref:
                    parser: output
                    parameters:
                        layer_name: firehose-rsc
                        output_name: CustomResourceFunctionArn
