---
meta:
    description:
        Creates an input and output Kinesis stream for an event processing pipeline
    parameters:
        input_stream:
            description:
                Properties of the input Kinesis stream
            value:
                shard_count: 1
                batch_size: 1
        output_stream:
            description:
                Properties of the output Kinesis stream
            value:
                shard_count: 1
                batch_size: 1
