---
meta:
    description:
        Creates a Firehose delivery stream using the custom CF resource
    parameters:
        custom_resource_function_arn:
            description:
                The ARN of the Lambda function that backs the custom Firehose resource
            value:
                ref:
                    parser: output
                    parameters:
                        layer_name: firehose-rsc
                        output_name: CustomResourceFunctionArn
